"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""
def solve(num):
	result = 0
	max = 2
	min = 1
	aux = 0
	count = 0
	while (max < num):
		if (max % 2 == 0):
			result += max
		aux = max
		max = max + min
		min = aux
	return result

if __name__=="__main__":
	print(solve(4000000))